#!/usr/bin/env python3
"""Check what content has been generated by the system."""
import os
import json
from pathlib import Path

print("=" * 60)
print("Checking Generated Content")
print("=" * 60)

# Check common output directories
output_dirs = [
    "./data/generated",
    "./generation/output",
    "./output/generated",
    "./logs",
]

found_content = False

for output_dir in output_dirs:
    dir_path = Path(output_dir)
    if dir_path.exists():
        print(f"\nChecking: {output_dir}")
        files = list(dir_path.rglob("*"))
        if files:
            found_content = True
            for file in files[:20]:  # Show first 20 files
                if file.is_file():
                    size = file.stat().st_size
                    print(f"  {file.name} ({size} bytes)")
                    # Try to read and show preview if it's a text file
                    if file.suffix in ['.txt', '.json', '.md', '.py']:
                        try:
                            with open(file, 'r', encoding='utf-8') as f:
                                content = f.read(200)
                                if content.strip():
                                    print(f"    Preview: {content[:100]}...")
                        except:
                            pass
        else:
            print(f"  (empty)")

if not found_content:
    print("\nNo generated content directories found.")
    print("Content may be stored in memory or not yet generated.")
    print("\nCheck the system logs for generation output.")

# Check for any recent JSON files that might contain generated content
print("\n" + "=" * 60)
print("Checking for recent JSON files (potential generated content)")
print("=" * 60)

json_files = []
for root, dirs, files in os.walk("."):
    # Skip common directories
    if any(skip in root for skip in ['__pycache__', '.git', 'venv', 'node_modules']):
        continue
    for file in files:
        if file.endswith('.json'):
            file_path = Path(root) / file
            try:
                mtime = file_path.stat().st_mtime
                json_files.append((file_path, mtime))
            except:
                pass

# Sort by modification time (newest first)
json_files.sort(key=lambda x: x[1], reverse=True)

if json_files:
    print(f"\nFound {len(json_files)} JSON files (showing 10 most recent):")
    for file_path, mtime in json_files[:10]:
        print(f"  {file_path} (modified: {mtime})")
        # Try to read and show structure
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                if isinstance(data, dict):
                    print(f"    Keys: {list(data.keys())[:5]}")
                elif isinstance(data, list):
                    print(f"    List with {len(data)} items")
        except:
            pass
else:
    print("No JSON files found")

print("\n" + "=" * 60)
print("To see real-time generation, check the system logs while running.")
print("=" * 60)
